//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiWebApiMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eMaterial
    {
        public int MaterialId { get; set; }
        public string name { get; set; }
        public string materialType { get; set; }
        public string materialClass { get; set; }
        public string dispoAttribute { get; set; }
        public decimal priceVar { get; set; }
        public decimal priceFix { get; set; }
        public string priceControll { get; set; }
        public string dispGroup { get; set; }
        public string purchGroup { get; set; }
    
        public virtual ePcb ePcb { get; set; }
    }
}
