//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiWebApiMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ePcb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ePcb()
        {
            this.eOrders = new HashSet<eOrder>();
        }
    
        public int PcbId { get; set; }
        public int pcbTypeId { get; set; }
        public int pcbClassId { get; set; }
        public string serialPrefix { get; set; }
        public int topThtPartCount { get; set; }
        public int topSmtPartCount { get; set; }
        public int botThtPartCount { get; set; }
        public int botSmtPartCount { get; set; }
        public int thtSolderJoints { get; set; }
        public int smtSolderJoints { get; set; }
        public float squareInch { get; set; }
        public System.DateTime activationDate { get; set; }
        public Nullable<System.DateTime> decomissionDate { get; set; }
    
        public virtual eMaterial eMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eOrder> eOrders { get; set; }
    }
}
