//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiWebApiMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eSerial
    {
        public int SerialId { get; set; }
        public Nullable<int> SerialIdEan { get; set; }
        public int OrderId { get; set; }
        public short status { get; set; }
        public int rootOrderId { get; set; }
    
        public virtual eOrder eOrder { get; set; }
    }
}
