//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpiWebApiMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EOSEntities : DbContext
    {
        public EOSEntities()
            : base("name=EOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<eMaterial> eMaterials { get; set; }
        public virtual DbSet<eOrder> eOrders { get; set; }
        public virtual DbSet<ePcb> ePcbs { get; set; }
        public virtual DbSet<eSerial> eSerials { get; set; }
        public virtual DbSet<rOrderProcess> rOrderProcesses { get; set; }
    }
}
